name: magic_lore
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  url_launcher: ^6.0.5

flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/volumes_images_capas/

    - assets/images/dominaria_united/story/capa/
    - assets/images/dominaria_united/story/content/
    - assets/images/dominaria_united/side_story/capa/
    - assets/images/dominaria_united/side_story/content/

    - assets/images/innistrad1/story/capa/
    - assets/images/innistrad1/story/content/
    - assets/images/innistrad1/side_story/capa/
    - assets/images/innistrad1/side_story/content/

    - assets/images/innistrad2/story/capa/
    - assets/images/innistrad2/story/content/
    - assets/images/innistrad2/side_story/capa/
    - assets/images/innistrad2/side_story/content/

    - assets/images/kaldheim/story/capa/
    - assets/images/kaldheim/story/content/
    - assets/images/kaldheim/side_story/capa/
    - assets/images/kaldheim/side_story/content/

    - assets/images/kamigawa/story/capa/
    - assets/images/kamigawa/story/content/
    - assets/images/kamigawa/side_story/capa/
    - assets/images/kamigawa/side_story/content/

    - assets/images/march_of_the_machine/story/capa/
    - assets/images/march_of_the_machine/story/content/
    - assets/images/march_of_the_machine/side_story/capa/
    - assets/images/march_of_the_machine/side_story/content/

    - assets/images/phyrexia/story/capa/
    - assets/images/phyrexia/story/content/
    - assets/images/phyrexia/side_story/capa/
    - assets/images/phyrexia/side_story/content/

    - assets/images/streets_of_new_capenna/story/capa/
    - assets/images/streets_of_new_capenna/story/content/
    - assets/images/streets_of_new_capenna/side_story/capa/
    - assets/images/streets_of_new_capenna/side_story/content/

    - assets/images/strixhaven/story/capa/
    - assets/images/strixhaven/story/content/
    - assets/images/strixhaven/side_story/capa/
    - assets/images/strixhaven/side_story/content/

    - assets/images/the_brothers_war/story/capa/
    - assets/images/the_brothers_war/story/content/
    - assets/images/the_brothers_war/side_story/capa/
    - assets/images/the_brothers_war/side_story/content/
    
    

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Planewalker
      fonts:
        - asset: assets/fonts/Planewalker.otf
        - asset: assets/fonts/PlanewalkerBoldItalic.otf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
